targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - lib/data/models/**.dart
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
