name: story_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <=3.3.8"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.3
  http: ^0.13.5
  image_picker: ^0.8.7+3
  intl: ^0.17.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/image/
